// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type {
	StoryblokRichtext,
	StoryblokMultilink,
	StoryblokAsset,
} from "../storyblok";
export interface Blog {
	title?: string;
	description?: StoryblokRichtext;
	component: "blog";
	_uid: string;
	[k: string]: unknown;
}

export interface Feature {
	name?: string;
	component: "feature";
	_uid: string;
	[k: string]: unknown;
}

export interface FooterItem {
	items?: Links[];
	component: "footer_item";
	_uid: string;
	[k: string]: unknown;
}

export interface Global {
	burger_menu?: Menu[];
	footer?: FooterItem[];
	component: "global";
	_uid: string;
	[k: string]: unknown;
}

export interface Grid {
	columns?: (
		| Blog
		| Feature
		| FooterItem
		| Global
		| Grid
		| Hero
		| Item
		| Links
		| Menu
		| MenuItem
		| Page
		| Robots
		| Section
		| SubMenu
		| Teaser
	)[];
	component: "grid";
	_uid: string;
	[k: string]: unknown;
}

export interface Hero {
	Title?: string;
	description?: StoryblokRichtext;
	component: "hero";
	_uid: string;
	[k: string]: unknown;
}

export interface Item {
	text?: string;
	component: "item";
	_uid: string;
	[k: string]: unknown;
}

export interface Links {
	text?: string;
	link?: Exclude<
		StoryblokMultilink,
		{ linktype?: "email" } | { linktype?: "asset" }
	>;
	component: "links";
	_uid: string;
	[k: string]: unknown;
}

export interface Menu {
	items?: MenuItem[];
	component: "menu";
	_uid: string;
	[k: string]: unknown;
}

export interface MenuItem {
	title?: string;
	link?: Exclude<
		StoryblokMultilink,
		{ linktype?: "email" } | { linktype?: "asset" }
	>;
	SubItems?: SubMenu[];
	component: "menu_item";
	_uid: string;
	[k: string]: unknown;
}

export interface Page {
	body?: (
		| Blog
		| Feature
		| FooterItem
		| Global
		| Grid
		| Hero
		| Item
		| Links
		| Menu
		| MenuItem
		| Page
		| Robots
		| Section
		| SubMenu
		| Teaser
	)[];
	robots?: Robots[];
	component: "page";
	_uid: string;
	[k: string]: unknown;
}

export interface Robots {
	index?: boolean;
	follow?: boolean;
	component: "robots";
	_uid: string;
	[k: string]: unknown;
}

export interface Section {
	title?: string;
	description?: StoryblokRichtext;
	action_btn_svg_icon?: StoryblokAsset;
	action_btn_text?: string;
	action_btn_link?: Exclude<
		StoryblokMultilink,
		{ linktype?: "email" } | { linktype?: "asset" }
	>;
	component: "Section";
	_uid: string;
	[k: string]: unknown;
}

export interface SubMenu {
	title?: string;
	link?: Exclude<
		StoryblokMultilink,
		{ linktype?: "email" } | { linktype?: "asset" }
	>;
	component: "sub_menu";
	_uid: string;
	[k: string]: unknown;
}

export interface Teaser {
	headline?: string;
	component: "teaser";
	_uid: string;
	[k: string]: unknown;
}
