// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type {
	StoryblokRichtext,
	StoryblokMultilink,
	StoryblokAsset,
} from "@/storyblok";
export interface Blog {
	title?: string;
	description?: StoryblokRichtext;
	component: "blog";
	_uid: string;
	[k: string]: unknown;
}

export interface StoryblokAsset {
  filename: string;
  alt?: string;
}

export interface Feature {
	name?: string;
	component: "feature";
	_uid: string;
	[k: string]: unknown;
}

export interface FooterItem {
  title?: string;
  items?: Links[];
  component: "footer_item";
  _uid: string;
  [k: string]: unknown;
}

export interface Global {
  header_logo?: StoryblokAsset;
	burger_menu?: Menu[];
	footer?: FooterGrid[];
	component: "global";
	_uid: string;
	[k: string]: unknown;
}

export interface Page {
	body?: (
		| Blog | Feature | FooterItem | Global | Grid | Hero | Item | Links | Menu | MenuItem | Page | Robots | Section | SubMenu | Teaser | BgHeroBanner | SectionWrapper | LeftCard | RightCard | IconBoxGrid | IconBoxItem | TextGroup | GoogleReviewsSlider | GoogleReviewItem | FooterGrid | FooterLogoBox | FooterItemBox | FooterTextGroup | SocialMediaLinks | ThreeImageShowcase | SmallTextGroup | SmallTextGroupGrid
	)[];
	robots?: Robots[];
	component: "page";
	_uid: string;
	[k: string]: unknown;
}

export interface Grid {
	columns?: (
		| Blog | Feature | FooterItem | Global | Grid | Hero | Item | Links | Menu | MenuItem | Page | Robots | Section | SubMenu | Teaser | BgHeroBanner | SectionWrapper | LeftCard | RightCard | IconBoxGrid | IconBoxItem | TextGroup | GoogleReviewsSlider | GoogleReviewItem | FooterGrid | FooterLogoBox | FooterItemBox | FooterTextGroup | SocialMediaLinks | ThreeImageShowcase | SmallTextGroup | SmallTextGroupGrid
	)[];
	component: "grid";
	_uid: string;
	[k: string]: unknown;
}

export interface SectionWrapper {
  bg_image?: StoryblokAsset;
  body?: (
    | Blog | Feature | FooterItem | Global | Grid | Hero | Item | Links | Menu | MenuItem | Page | Robots | Section | SubMenu | Teaser | BgHeroBanner | SectionWrapper | LeftCard | RightCard | IconBoxGrid | IconBoxItem | TextGroup | GoogleReviewsSlider | GoogleReviewItem | FooterGrid | FooterLogoBox | FooterItemBox | FooterTextGroup | SocialMediaLinks | ThreeImageShowcase | SmallTextGroup | SmallTextGroupGrid
  )[];
  gap_size?: "extra-small" | "small" | "medium" | "large";
  overflow?: "hidden" | "visible";
  component: "section_wrapper";
  _uid: string;
  [k: string]: unknown;
}

export interface IconBoxGrid {
  bg_image?: StoryblokAsset;
  max_width?: string;
  top_content?: (
    | Blog | Feature | FooterItem | Global | Grid | Hero | Item | Links | Menu | MenuItem | Page | Robots | Section | SubMenu | Teaser | BgHeroBanner | SectionWrapper | LeftCard | RightCard | IconBoxGrid | IconBoxItem | TextGroup | GoogleReviewsSlider | GoogleReviewItem | FooterGrid | FooterLogoBox | FooterItemBox | FooterTextGroup | SocialMediaLinks | ThreeImageShowcase | SmallTextGroup | SmallTextGroupGrid
  )[];
  items?: IconBoxItem[];
  component: "icon_box_grid";
  _uid: string;
  [k: string]: unknown;
}

export interface SmallTextGroupGrid {
  items?: (
    | SmallTextGroup
  )[];
  component: "small_text_group_grid";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterGrid {
  bg_image?: StoryblokAsset;
  columns?: (FooterLogoBox | FooterItemBox)[];
  copyright_text?: string;
  component: "footer_grid";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterItemBox {
  columns?: (
     | FooterItem | FooterContactBox
  )[];
  component: "footer_item_box";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterContactBox {
  columns?: (
    | FooterTextGroup
    | SocialMediaLinks
  )[];
  component: "footer_contact_box";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterLogoBox {
  title_1?: string;
  title_2?: string;
  title_3?: string;
  logo?: StoryblokAsset;
  component: "footer_logo_box";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterTextGroup {
  title?: string;
  text?: StoryblokRichtext;
  component: "footer_text_group";
  _uid: string;
  [k: string]: unknown;
}

export interface SocialMediaLinks {
  links?: SocialMediaItem[];
  component: "social_media_links";
  _uid: string;
  [k: string]: unknown;
}

export interface SocialMediaItem {
  icon?: StoryblokAsset;
  url?: StoryblokMultilink;
  component: "social_media_item";
  _uid: string;
  [k: string]: unknown;
}

export interface ThreeImageShowcase {
  images?: StoryblokAsset[];
  gap_size?: "small" | "medium" | "large";
  radius_size?: "small" | "medium" | "large";
  component: "three_image_showcase";
  _uid: string;
  [k: string]: unknown;
}

export interface Hero {
	Title?: string;
	description?: StoryblokRichtext;
	component: "hero";
	_uid: string;
	[k: string]: unknown;
}

export interface IconBoxItem {
  image?: StoryblokAsset;
  title?: string;
  description?: StoryblokRichtext;
  component: "icon_box_item";
  _uid: string;
  [k: string]: unknown;
}

export interface TextGroup {
  title?: string;
  description?: StoryblokRichtext;
  component: "text_group";
  _uid: string;
  [k: string]: unknown;
}

export interface BgHeroBanner {
  bg_image?: StoryblokAsset;
  main_image?: StoryblokAsset;
  overlay?: boolean;
  component: "bg_hero_banner";
  _uid: string;
  [k: string]: unknown;
}

export interface LeftCard {
  image?: StoryblokAsset;
  title?: string;
  description?: StoryblokRichtext;
  link?: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  link_text?: string;
  component: "left_card";
  _uid: string;
  [k: string]: unknown;
}

export interface RightCard {
  image?: StoryblokAsset;
  title?: string;
  description?: StoryblokRichtext;
  link?: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  link_text?: string;
  component: "right_card";
  _uid: string;
  [k: string]: unknown;
}

export interface GoogleReviewItem {
  name?: string;
  subtitle?: string;
  rating?: number;
  text?: StoryblokRichtext;
  cta_label?: string;
  component: "google_review_item";
  _uid: string;
  [k: string]: unknown;
}

export interface GoogleReviewsSlider {
  title?: string;
  rating_label?: string;
  reviews_note?: string;
  reviews?: GoogleReviewItem[];
  component: "google_reviews_slider";
  _uid: string;
  [k: string]: unknown;
}

export interface Item {
	text?: string;
	component: "item";
	_uid: string;
	[k: string]: unknown;
}

export interface Links {
	text?: string;
	link?: Exclude<
		StoryblokMultilink,
		{ linktype?: "email" } | { linktype?: "asset" }
	>;
	component: "links";
	_uid: string;
	[k: string]: unknown;
}

export interface Menu {
	items?: MenuItem[];
	component: "menu";
	_uid: string;
	[k: string]: unknown;
}

export interface MenuItem {
	title?: string;
	link?: Exclude<
		StoryblokMultilink,
		{ linktype?: "email" } | { linktype?: "asset" }
	>;
	SubItems?: SubMenu[];
	component: "menu_item";
	_uid: string;
	[k: string]: unknown;
}

export interface SmallTextGroup {
  title?: string;
  description?: StoryblokRichtext;
  component: "small_text_group";
  _uid: string;
  [k: string]: unknown;
}

export interface Robots {
	index?: boolean;
	follow?: boolean;
	component: "robots";
	_uid: string;
	[k: string]: unknown;
}

export interface Section {
	title?: string;
	description?: StoryblokRichtext;
	action_btn_svg_icon?: StoryblokAsset;
	action_btn_text?: string;
	action_btn_link?: Exclude<
		StoryblokMultilink,
		{ linktype?: "email" } | { linktype?: "asset" }
	>;
	component: "Section";
	_uid: string;
	[k: string]: unknown;
}

export interface SubMenu {
	title?: string;
	link?: Exclude<
		StoryblokMultilink,
		{ linktype?: "email" } | { linktype?: "asset" }
	>;
	component: "sub_menu";
	_uid: string;
	[k: string]: unknown;
}

export interface Teaser {
	headline?: string;
	component: "teaser";
	_uid: string;
	[k: string]: unknown;
}

export interface Form {
  action_url?: string;
  method?: "POST" | "GET";
  success_message?: string;
  error_message?: string;
  button_label?: string;
  fields?: (FormInput | FormTextarea)[];
  component: "form";
  _uid: string;
  [k: string]: unknown;
}

export interface FormColumns {
  columns?: 1 | 2 | 3;
  fields?: (
    | FormInput
    | FormTextarea
  )[];
  component: "form_columns";
  _uid: string;
  [k: string]: unknown;
}

export interface FormInput {
  name?: string;
  label?: string;
  type?: "text" | "email" | "number" | "password" | "tel";
  required?: boolean;
  placeholder?: string;
  help_text?: string;
  component: "form_input";
  _uid: string;
  [k: string]: unknown;
}

export interface FormTextarea {
  name?: string;
  label?: string;
  required?: boolean;
  placeholder?: string;
  rows?: number;
  help_text?: string;
  component: "form_textarea";
  _uid: string;
  [k: string]: unknown;
}

export interface ContactFormGrid {
  bg_color?: string;
  border_color?: string;
  border_radius?: number;
  bg_image?: StoryblokAsset;
  max_width?: "default" | "wide" | "full";
  columns?: (ImageBox | ContactFormBox)[];
  align?: "left" | "center" | "right";
  component: "contact_form_grid";
  _uid: string;
  [k: string]: unknown;
}

export interface ImageBox {
  image?: StoryblokAsset;
  width_type?: "%" | "px";
  width_value?: number;
  border_radius?: number;
  object_fit?: "cover" | "contain";
  component: "image_box";
  _uid: string;
  [k: string]: unknown;
}

export interface TextBlock {
  title?: string;
  description?: StoryblokRichtext;
  align?: "left" | "center" | "right";
  component: "text_block";
  _uid: string;
  [k: string]: unknown;
}

export interface ContactFormBox {
  width_type?: "%" | "px";
  width_value?: number;
  padding?: "none" | "large";
  children?: (
    | TextBlock 
    | Form
    | FormInput
    | FormTextarea
  )[];
  component: "contact_form_box";
  _uid: string;
  [k: string]: unknown;
}